#!/bin/bash

# This function takes two arguments:
# - $1 is the NAME of the path variable that we want to extend
# - $2 is the string that we want to prepend to that path.
prepend_path () {
	if [ "$#" -ne 2 ]; then
		echo "prepend_path() Illegal number of parameters: $#"
	fi
	# If the path variable is the empty string
	if [[ -z "${!1}" ]]; then
		export ${1}="$2"; # Simply use the new path
	else
		export ${1}="$2:${!1}"; # Otherwise prepend the new path
	fi
}

