image: revng/revng-build-dependencies:latest

stages:
  - build

create-binaries:
  stage: build
  script:
  - support/install-dependencies.sh
  - git checkout -B "$CI_COMMIT_REF_NAME" "$CI_COMMIT_SHA"
  - make create-binary-archive-all commit-binary-archive
